// ─── Mock Data ────────────────────────────────────────────────────────────────

const MOCK_USERS = [
  {
    id: "u1",
    email: "alice@example.com",
    password: "password",
    name: "Alice Martin",
    age: 34,
    treatments: [
      { id: "t1", name: "Myopie -3.5 dioptries", type: "vision", since: "2019" },
      { id: "t2", name: "Allergie aux acariens", type: "allergie", since: "2015" },
    ],
    photo: null,
  },
];

const MOCK_PRODUCTS = [
  // ─── Lentilles ──────────────────────────────────────────────────────────────
  {
    id: "p1",
    category: "lentilles",
    name: "EcoLens Daily Comfort",
    brand: "BioOptics",
    tagline: "Lentilles journalières 100 % bio-sourcées",
    match: 96,
    tags: ["bio", "vegan", "recyclable"],
    image: "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=600&q=80",
    indication: "Myopie jusqu'à -6 dioptries",
    specs: { correction: "-3.50", diameter: "14.2mm", power: "-3.50 D", wearing: "Journalier" },
    ethics: {
      manufacturer: "BioOptics SAS",
      country: "France",
      city: "Lyon",
      founded: "2015",
      certifications: ["ISO 13485", "CE", "Cruelty Free"],
      employees: 120,
      workerConditions: "Salaires 18 % au-dessus de la convention, crèche d'entreprise",
      animalTesting: false,
      vegan: true,
    },
    supply: {
      rawMaterial: "Polymère HEMA bio-sourcé (maïs non-OGM, Bretagne)",
      packagingMaterial: "Papier recyclé FSC + blister PET recyclé à 80 %",
      supplyChain: "Matière → Lyon → Conditionnement Genève → Distribution FR/CH/BE",
      co2PerUnit: 0.42, // kg CO2eq
      waterLitersPerUnit: 1.8,
      transportMode: "Camion électrique inter-sites",
    },
    cost: {
      manufacturingCost: 0.38, // € par lentille
      retailPrice: 1.2,
      margin: 68,
      compareMarket: "Marché moyen : 0.95 € / lentille",
    },
    endOfLife: "Collecte en pharmacie partenaire, recyclage via TerraCycle",
    score: { ethical: 91, environmental: 87, social: 89, transparency: 95 },
    alternatives: ["p2", "p3"],
  },
  {
    id: "p2",
    category: "lentilles",
    name: "ClearView Monthly Pro",
    brand: "OptiCorp",
    tagline: "Lentilles mensuelles silicone hydrogel",
    match: 83,
    tags: ["mensuel", "confort"],
    image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=600&q=80",
    indication: "Myopie, Hypermétropie, Astigmatisme",
    specs: { correction: "-3.50", diameter: "14.0mm", power: "-3.50 D", wearing: "30 jours" },
    ethics: {
      manufacturer: "OptiCorp GmbH",
      country: "Allemagne",
      city: "Munich",
      founded: "1998",
      certifications: ["ISO 13485", "CE"],
      employees: 4800,
      workerConditions: "Convention collective standard",
      animalTesting: true,
      vegan: false,
    },
    supply: {
      rawMaterial: "Silicone hydrogel synthétique",
      packagingMaterial: "Plastique PET vierge",
      supplyChain: "Matière Asie → Fabrication Munich → Distribution mondiale",
      co2PerUnit: 2.1,
      waterLitersPerUnit: 8.4,
      transportMode: "Transport aérien partiel",
    },
    cost: {
      manufacturingCost: 2.10,
      retailPrice: 28.90,
      margin: 93,
      compareMarket: "Marché moyen : 22 € / boite 6",
    },
    endOfLife: "Poubelle ordinaire",
    score: { ethical: 52, environmental: 41, social: 60, transparency: 48 },
    alternatives: ["p1", "p3"],
  },
  {
    id: "p3",
    category: "lentilles",
    name: "NaturalSight Bi-Weekly",
    brand: "GreenOptic",
    tagline: "Lentilles bi-mensuelles fabriquées en Europe responsable",
    match: 79,
    tags: ["europe", "transparent"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80",
    indication: "Myopie jusqu'à -8 dioptries",
    specs: { correction: "-3.50", diameter: "14.2mm", power: "-3.50 D", wearing: "15 jours" },
    ethics: {
      manufacturer: "GreenOptic S.p.A",
      country: "Italie",
      city: "Milan",
      founded: "2009",
      certifications: ["ISO 13485", "CE", "B Corp"],
      employees: 340,
      workerConditions: "Participation aux bénéfices, télétravail, bilan carbone individuel",
      animalTesting: false,
      vegan: true,
    },
    supply: {
      rawMaterial: "Copolymère HEMA/MMA recyclé post-industriel",
      packagingMaterial: "Carton FSC, plastique à 60 % recyclé",
      supplyChain: "Matière Milan → Fabrication Milan → Logistique Suisse → EU",
      co2PerUnit: 0.71,
      waterLitersPerUnit: 3.1,
      transportMode: "Train + Camion hybride",
    },
    cost: {
      manufacturingCost: 1.20,
      retailPrice: 18.50,
      margin: 85,
      compareMarket: "Marché moyen : 15 € / boite bi-mensuelle",
    },
    endOfLife: "Retour fabricant, filière recyclage fermée",
    score: { ethical: 82, environmental: 78, social: 84, transparency: 80 },
    alternatives: ["p1", "p2"],
  },
  // ─── Prothèse ────────────────────────────────────────────────────────────────
  {
    id: "p4",
    category: "prothese",
    name: "ReWalk Knee Éco",
    brand: "MédTech Vert",
    tagline: "Prothèse de genou en bioplastique PLA recyclé",
    match: 88,
    tags: ["bioplastique", "local", "recyclable"],
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80",
    indication: "Amputation trans-tibiale / trans-fémorale",
    specs: { material: "PLA + fibres de lin", weight: "620g", sizing: "XS–XL", adjustable: true },
    ethics: {
      manufacturer: "MédTech Vert SCOP",
      country: "France",
      city: "Toulouse",
      founded: "2017",
      certifications: ["ISO 13485", "CE Classe IIa", "Entreprise solidaire d'utilité sociale"],
      employees: 45,
      workerConditions: "SCOP — tous salariés co-propriétaires, grille salariale transparente",
      animalTesting: false,
      vegan: true,
    },
    supply: {
      rawMaterial: "PLA issu d'amidon de maïs (Occitanie) + lin (Normandie)",
      packagingMaterial: "Mousse liège naturel, carton recyclé",
      supplyChain: "Fibres FR → Impression 3D Toulouse → Livraison direct hôpital",
      co2PerUnit: 3.2,
      waterLitersPerUnit: 12,
      transportMode: "Camion < 200 km",
    },
    cost: {
      manufacturingCost: 420,
      retailPrice: 1200,
      margin: 65,
      compareMarket: "Marché moyen : 3 500 € — remboursement sécu. partiel",
    },
    endOfLife: "Reprise fabricant → broyage → nouveau filament",
    score: { ethical: 94, environmental: 88, social: 96, transparency: 93 },
    alternatives: ["p5"],
  },
  {
    id: "p5",
    category: "prothese",
    name: "OrthoPlus Classic",
    brand: "MedGlobal",
    tagline: "Prothèse de genou en polypropylène haute résistance",
    match: 71,
    tags: ["résistant", "standard"],
    image: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&q=80",
    indication: "Amputation trans-tibiale",
    specs: { material: "Polypropylène PP", weight: "890g", sizing: "S–XL", adjustable: false },
    ethics: {
      manufacturer: "MedGlobal Corp.",
      country: "États-Unis",
      city: "Chicago",
      founded: "1985",
      certifications: ["FDA", "CE"],
      employees: 12000,
      workerConditions: "Convention standard US, aucune information sur les sous-traitants",
      animalTesting: true,
      vegan: false,
    },
    supply: {
      rawMaterial: "Polypropylène vierge (pétrochimie, Texas)",
      packagingMaterial: "Polystyrène expansé + carton",
      supplyChain: "Matière TX → Fabrication Chicago → Livraison mondiale (avion)",
      co2PerUnit: 18.4,
      waterLitersPerUnit: 42,
      transportMode: "Cargo aérien",
    },
    cost: {
      manufacturingCost: 310,
      retailPrice: 3500,
      margin: 91,
      compareMarket: "Marché moyen : 3 500 €",
    },
    endOfLife: "Déchets plastiques spéciaux hospitaliers",
    score: { ethical: 38, environmental: 29, social: 44, transparency: 31 },
    alternatives: ["p4"],
  },
  // ─── Médicament ──────────────────────────────────────────────────────────────
  {
    id: "p6",
    category: "medicament",
    name: "AllerStop BIO",
    brand: "Phytolab",
    tagline: "Antihistaminique naturel à base de quercétine",
    match: 74,
    tags: ["naturel", "sans ordonnance", "vegan"],
    image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&q=80",
    indication: "Rhinite allergique, allergie saisonnière",
    specs: { dosage: "400mg / gélule", frequency: "2x / jour", duration: "selon symptômes", form: "Gélule végétale" },
    ethics: {
      manufacturer: "Phytolab Lab SAS",
      country: "France",
      city: "Bordeaux",
      founded: "2011",
      certifications: ["BPF (Bonnes Pratiques de Fabrication)", "CE", "Vegan Society"],
      employees: 78,
      workerConditions: "Flexibilité horaire, télétravail 3j/sem, parité stricte encadrement",
      animalTesting: false,
      vegan: true,
    },
    supply: {
      rawMaterial: "Quercétine extraite d'oignons (agriculture bio France)",
      packagingMaterial: "Flacon verre recyclé, notice papier recyclé, boîte carton FSC",
      supplyChain: "Plantes FR → Extraction Bordeaux → Gélulage Bordeaux → Pharmacies",
      co2PerUnit: 0.18,
      waterLitersPerUnit: 0.9,
      transportMode: "Route France uniquement",
    },
    cost: {
      manufacturingCost: 3.20,
      retailPrice: 14.90,
      margin: 79,
      compareMarket: "Antihistaminiques synthétiques : 8–12 € / boîte",
    },
    endOfLife: "Flacon verre → collecte pharmacie → recyclerie",
    score: { ethical: 88, environmental: 84, social: 90, transparency: 86 },
    alternatives: ["p7"],
  },
  {
    id: "p7",
    category: "medicament",
    name: "Loratadine GNR 10mg",
    brand: "Pharma Générique",
    tagline: "Antihistaminique générique — cétirizine 10mg",
    match: 65,
    tags: ["générique", "remboursé"],
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80",
    indication: "Rhinite allergique, urticaire, allergie acariens",
    specs: { dosage: "10mg / comprimé", frequency: "1x / jour", duration: "selon ordonnance", form: "Comprimé" },
    ethics: {
      manufacturer: "GenPharm India Ltd.",
      country: "Inde",
      city: "Hyderabad",
      founded: "2003",
      certifications: ["WHO GMP", "CE"],
      employees: 6200,
      workerConditions: "Données non divulguées publiquement",
      animalTesting: true,
      vegan: false,
    },
    supply: {
      rawMaterial: "Loratadine synthétique (matière première Chine)",
      packagingMaterial: "Blister aluminium + PVC, notice papier, boîte carton standard",
      supplyChain: "Principe actif CN → Fabrication IN → Import EU → Distribution pharmacie",
      co2PerUnit: 1.4,
      waterLitersPerUnit: 5.6,
      transportMode: "Maritime + Route",
    },
    cost: {
      manufacturingCost: 0.45,
      retailPrice: 3.20,
      margin: 86,
      compareMarket: "Remboursé sécu. (taux 30 %)",
    },
    endOfLife: "Collecte Cyclamed en pharmacie",
    score: { ethical: 44, environmental: 38, social: 40, transparency: 35 },
    alternatives: ["p6"],
  },
];

const CONDITION_PRODUCT_MAP = {
  "myopie": ["p1", "p2", "p3"],
  "hypermétropie": ["p1", "p2", "p3"],
  "astigmatisme": ["p2", "p3"],
  "presbytie": ["p2"],
  "lentilles": ["p1", "p2", "p3"],
  "prothèse": ["p4", "p5"],
  "genou": ["p4", "p5"],
  "allergie": ["p6", "p7"],
  "acariens": ["p6", "p7"],
  "rhinite": ["p6", "p7"],
  "antihistaminique": ["p6", "p7"],
};

function searchProducts(query) {
  const q = query.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  let ids = new Set();
  for (const [key, vals] of Object.entries(CONDITION_PRODUCT_MAP)) {
    const k = key.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (q.includes(k) || k.includes(q)) vals.forEach(v => ids.add(v));
  }
  if (ids.size === 0) MOCK_PRODUCTS.forEach(p => ids.add(p.id));
  return MOCK_PRODUCTS.filter(p => ids.has(p.id));
}
